name: ecommerce-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.*
  - numpy=1.21.*
  - scipy=1.9.*
  - scikit-learn=1.1.*
  - matplotlib=3.5.*
  - seaborn=0.11.*
  - plotly=5.10.*
  - jupyter=1.0.*
  - ipykernel=6.15.*
  - statsmodels=0.13.*
  - sqlalchemy=1.4.*
  - requests=2.28.*
  - pip
  - pip:
    - streamlit>=1.12.0
    - dash>=2.6.0
    - dash-bootstrap-components>=1.2.0
    - xgboost>=1.6.0
    - lightgbm>=3.3.0
    - prophet>=1.1.0
    - pmdarima>=2.0.0
    - category-encoders>=2.5.0
    - imbalanced-learn>=0.9.0
    - missingno>=0.5.0
    - yellowbrick>=1.5.0
    - python-dotenv>=0.20.0
    - fpdf2>=2.5.0
    - openpyxl>=3.0.0